name: Create Release Assets

on:
  release:
    types: [ created ]

jobs:
  publish-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload all scripts as release assets
        uses: softprops/action-gh-release@v1
        with:
          files: scripts/*.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}